# Forward Evolution: From 0.0 Myr to 500.0 Myr
# Bar + Axisymmetric Potential (Main Component)
[Potential main]
file=MWPotentialHunter24_full.ini
rotation=[[0.00000000, 18.73544350], [0.51134516, -0.44000000]]

# Spiral Arms Potential
[Potential spiral]
file=MWPotentialHunter24_spiral.ini
rotation=[[0.00000000, 11.06526610], [0.51134516, -0.44000000]]
