# use mcluster to generate a star cluster with the initial condtion: 
# N=1000
# Kroupa (2001) IMF
# half-mass radius of 1 pc
# a Plummer density profile
# units in astronomical units (Msun, pc, km/s)
# The option '-C 5' is used to create initial conditions for NBODY6++GPU, which will be used to generate initial conditions for PeTar.
mcluster -N 1000 -R 1 -C 5 -u 1 >mc.log

# use petar.init to create initial data for petar.
# the mcluster option '-u 1' generate data in astronomical unit (Msun, pc, km/s), but petar requires a self-consistent unit of velocity: pc/Myr, '-v kms2pcmyr' will do this.
# the external potential using agama is switched on by '-t'
# the central position and velocity of cluster '-c x[pc],y,z,vx[km/s],vy,vz' in the galactic central frame is needed
petar.init -c 8000,0,0,0,-180,0 -t -v kms2pcmyr -f input test.dat.10

# Use PeTar to execute the simulation.
# Use '-t 500.0' to run the simulation for 500 Myr.
# Use '-o 1.0' to generate output snapshots every 1 Myr.
# Use '-u 1' to set the units to astronomical units (Msun, pc, pc/Myr).
# Parallel hint: this is a non-binaries N~10^3 sample, where one thread is usually efficient.
# If needed, set 'OMP_NUM_THREADS=[number of threads]' and benchmark on your machine.
# set 'OMP_STACKSIZE' to ensure sufficient stack memory for each thread, otherwise segmentation faults may occur.
# To switch on Agama potential package, the option '--with-external=agama' is needed during configuration of petar.
# To use Agama, it is necessary to generate the potential file with Agama, and the option '--agama-conf-file' is used to specify the configuration file for Agama potential. 
# The example configuration file 'MWpotentialHunter24_rotspiral.ini' is generated by Agama official example script and petar.agama python module.
# It is the MilkyWay potential from Hunter et al. (2024) with a rotating spiral arm, see 'example_mw_potential_hunter24.py' in Agama py samples for details.
# First run 'example_mw_potential_hunter24.py' from Agama py samples to generate 'MWPotentialHunter24_full.ini' and 'MWPotentialHunter24_spiral.ini'
# Then in python, import petar and use 
# petar.agama.createMWPotentialHunter24ConstRotationConfig('MWpotentialHunter24_rotspiral.ini', evolve_duration=500)
# to create the configuration file for Agama potential with a rotating bar and spiral arm, 
# where 'evolve_duration' is the duration of simulation, which assume the ending phase has bar/spiral arm of present-day positions.
OMP_NUM_THREADS=1 OMP_STACKSIZE=128M petar -u 1 --agama-conf-file MWpotentialHunter24_rotspiral.ini -t 500.0 -o 1.0 input &>output

# after mode finished, gether the output data and do post-data process to detect binaries, obtain Lagrangian and core radii and corresponding properties.
# To maintain consistent units during post-processing, use '-G 0.00449830997959438' to set the gravitational constant to astronomical units.
petar.data.gether data
petar.data.process -t agama --r-escape tidal -G 0.00449830997959438 data.snap.lst

# generate configure file to plot MWPotential map (see petar.external -h for details). Parameter meaning:
# 0: initial time; 1: time interval for update potential;
# 500: snapshot number for potential map; 1: output time interval for potential map
# -10000 10000 1000: x range and number of grid points for potential map;
# -10000 10000 1000: y range and number of grid points for potential map;
# -500 500 50: z range and number of grid points for potential map.
echo '0 1 500 1 -10000 10000 1000 -10000 10000 1000 -500 500 50' > pot_conf
# use petar.external to generate potential map from Agama potential for each snapshot, which will be used for the movie of the simulation with external potential.
# The option '-m pot_conf' is used to specify the configuration file for generating potential map, which is created in the previous step.
# The option '-p input.par' is used to specify the parameter file for the simulation, which is needed to read the information of the external potential from the parameter file (generated by petar).
petar.external -p input.par -m pot_conf

# use petar.movie to make a movie of the simulation (movie.mp4).
# The option '-i no' indicate no stellar evolution.
# The option '-t agama' indicate Agama potential is used
# The option '-m x-y,x-y' is used to specify the projection of the movie, which is in the x-y plane in this case with two panels.
# The option '-R 50,10000' is used to set the radius of the plot to 50 and 10000 pc for each panel, which can be adjusted according to the size of the cluster and the desired field-of-view.
# The option '--marker-scale 1,0.1' is used to set the marker scale for the particles in the movie, which can be adjusted according to the desired visibility of the particles in the movie.
# The option '--cm-mode core,none' is used to specify the center of mass mode for the movie, which can be set to 'core' to use the core as the center of mass or 'none' to not use any center of mass. 
# In this case, the first panel uses the core as the center of mass, while the second panel does not use any center of mass.
# The option '--dpi 300' is used to set the resolution of the movie, which can be adjusted according to the desired quality and file size of the movie.
# petar.movie -i no -t agama -m x-y,x-y -R 50,10000 --marker-scale 1,0.1 --cm-mode core,none --ext-pot  --ext-pot-log --ext-pot-with-contour --dpi 300 data.snap.lst

# Add one more x-z plot and set plotting x, y limits manually: 
petar.movie -i no -t agama -m x-y,x-y,x-z --x-min -50,-10000,-10000 --x-max 50,10000,10000 --y-min -50,-10000,-500 --y-max 50,10000,500 --marker-scale 1,0.1,0.1 --cm-mode core,none,none --ext-pot  --ext-pot-log --ext-pot-with-contour --dpi 300 data.snap.lst