#!/usr/bin/env python3
"""Generate src/astro_units.hpp using astropy's IAU/CODATA constants.

This script computes PeTar's unit-system constants from astropy's
authoritative definitions and writes them to astro_units.hpp.

Usage:
    # Generate (overwrite) astro_units.hpp:
    python tools/generate_astro_units.py

    # Verify existing header matches astropy within a relative tolerance:
    python tools/generate_astro_units.py --check

    # Print values only (no file I/O):
    python tools/generate_astro_units.py --print
"""

import argparse
import datetime
import re
import sys
from pathlib import Path

import astropy
import astropy.constants as const
import astropy.units as u

REPO_ROOT = Path(__file__).resolve().parents[1]
HEADER_PATH = REPO_ROOT / "src" / "astro_units.hpp"

# ── Helper: convert a quantity to PeTar base units ──────────────────────


def in_units(quantity, target_unit: str) -> float:
    """Convert an astropy Quantity to a float in *target_unit* string form."""
    return quantity.to(target_unit).value


# ── Compute all constants from astropy ──────────────────────────────────


def compute_constants() -> dict:
    # All unit conversions use astropy.to() with composite unit strings.
    # astropy handles the dimensional analysis automatically.

    # G in pc^3 / (Msun * Myr^2)
    G_pc3_Msun_Myr2 = const.G.to("pc^3 / (M_sun * Myr^2)").value

    # pc / Myr → km / s
    pc_Myr_to_km_s = (1.0 * u.pc / u.Myr).to(u.km / u.s).value

    # km / s → pc / Myr  (inverse)
    km_s_to_pc_Myr = (1.0 * u.km / u.s).to(u.pc / u.Myr).value

    # pc → Rsun
    pc_to_Rsun = (1.0 * const.pc / const.R_sun).value

    # c in pc / Myr
    c_pc_Myr = const.c.to("pc / Myr").value

    return {
        "G_ASTRO": G_pc3_Msun_Myr2,
        "PC_TO_RSUN": pc_to_Rsun,
        "PCMYR_TO_KMS": pc_Myr_to_km_s,
        "KMS_TO_PCMYR": km_s_to_pc_Myr,
        "SPEED_OF_LIGHT": c_pc_Myr,
    }


# ── Format as C header ──────────────────────────────────────────────────


COMMENT = {
    "G_ASTRO": "pc^3/(Msun*Myr^2)",
    "PC_TO_RSUN": "pc -> rsun",
    "PCMYR_TO_KMS": "pc/Myr -> km/s",
    "KMS_TO_PCMYR": "km/s -> pc/Myr",
    "SPEED_OF_LIGHT": "speed of light pc/Myr",
}


def format_header(constants: dict) -> str:
    timestamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    astropy_ver = astropy.__version__
    python_ver = sys.version.split()[0]
    lines = [
        "#pragma once",
        "",
        "// Auto-generated by tools/generate_astro_units.py — do not edit manually.",
        f"// Generated: {timestamp}",
        f"// Python: {python_ver}  astropy: {astropy_ver}",
        "// To regenerate: python tools/generate_astro_units.py",
        "",
    ]
    for name in ["G_ASTRO", "PC_TO_RSUN", "PCMYR_TO_KMS", "KMS_TO_PCMYR", "SPEED_OF_LIGHT"]:
        val = float(constants[name])
        # Format with full double precision
        lines.append(f"#define {name:<20} {val:.16g}   // {COMMENT[name]}")
    lines.append("")
    return "\n".join(lines)


# ── Parse existing header for verification ──────────────────────────────


def parse_header(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(
        r"^\s*#define\s+(\w+)\s+([+\-]?(?:\d+\.?\d*|\d*\.\d+)(?:[eE][+\-]?\d+)?)"
    )
    constants = {}
    for line in text.splitlines():
        m = pattern.match(line)
        if m is not None:
            constants[m.group(1)] = float(m.group(2))
    return constants


# ── CLI ─────────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify existing header matches astropy values",
    )
    parser.add_argument(
        "--print",
        action="store_true",
        help="Print computed values only (no file I/O)",
    )
    parser.add_argument(
        "--rtol",
        type=float,
        default=1e-12,
        help="Relative tolerance for --check (default 1e-12)",
    )
    args = parser.parse_args()

    computed = compute_constants()

    if args.print:
        for name in ["G_ASTRO", "PC_TO_RSUN", "PCMYR_TO_KMS", "KMS_TO_PCMYR", "SPEED_OF_LIGHT"]:
            print(f"{name:<20} {float(computed[name]):.16g}")
        return

    if args.check:
        if not HEADER_PATH.exists():
            print(f"ERROR: {HEADER_PATH} not found")
            return 1
        existing = parse_header(HEADER_PATH)
        all_ok = True
        for name in ["G_ASTRO", "PC_TO_RSUN", "PCMYR_TO_KMS", "KMS_TO_PCMYR", "SPEED_OF_LIGHT"]:
            if name not in existing:
                print(f"  MISSING  {name}")
                all_ok = False
                continue
            e = existing[name]
            c = float(computed[name])
            reldiff = abs(e - c) / abs(c)
            status = "OK" if reldiff <= args.rtol else "DRIFT"
            marker = "" if status == "OK" else " ⚠"
            print(f"  {status:6s}  {name:<20}  existing={e:.16g}  astropy={c:.16g}  rel_diff={reldiff:.2e}{marker}")
            if status == "DRIFT":
                all_ok = False
        if all_ok:
            print("All constants match astropy within rtol={}.".format(args.rtol))
        else:
            print("Some constants have drifted. Re-run without --check to regenerate.")
        return

    # Default: generate header
    header_text = format_header(computed)
    HEADER_PATH.write_text(header_text, encoding="utf-8")
    print(f"Generated {HEADER_PATH}")
    for name in ["G_ASTRO", "PC_TO_RSUN", "PCMYR_TO_KMS", "KMS_TO_PCMYR", "SPEED_OF_LIGHT"]:
        print(f"  {name:<20} {float(computed[name]):.16g}")


if __name__ == "__main__":
    main()
