#pragma once

// Auto-generated by tools/generate_astro_units.py — do not edit manually.
// Generated: 2026-07-07 08:33:29 UTC
// Python: 3.12.12  astropy: 7.2.0
// To regenerate: python tools/generate_astro_units.py

#define G_ASTRO              0.004498502151469553   // pc^3/(Msun*Myr^2)
#define PC_TO_RSUN           44353565.92628098   // pc -> rsun
#define PCMYR_TO_KMS         0.9777922216807892   // pc/Myr -> km/s
#define KMS_TO_PCMYR         1.022712165045695   // km/s -> pc/Myr
#define SPEED_OF_LIGHT       306601.3937855506   // speed of light pc/Myr
