# Auto-generated by tools/generate_astro_units.py — do not edit manually.
# Generated: 2026-10-04 02:20:41 UTC
# Python: 3.12.3  astropy: 8.0.1
# To regenerate: python tools/generate_astro_units.py
# Kept in sync with src/astro_units.hpp by the same generator.

G_ASTRO = 0.004498502151469553  # pc^3/(Msun*Myr^2)
PC_TO_RSUN = 44353565.92628098  # pc -> rsun
PCMYR_TO_KMS = 0.9777922216807892  # pc/Myr -> km/s
KMS_TO_PCMYR = 1.022712165045695  # km/s -> pc/Myr
SPEED_OF_LIGHT = 306601.3937855506  # speed of light pc/Myr
